In [2]:
import matplotlib.pyplot as plt
import numpy as np
import time
import datetime as dt
import pandas as pd
# Import datasets, classifiers and performance metrics
from sklearn import datasets, svm, metrics


In [2]:
#from sklearn.cross_validation import train_test_split

In [3]:
train_data=pd.read_csv('mnist_train.csv')
test_data=pd.read_csv('mnist_test.csv')

In [4]:
train_images = train_data.iloc[:,1:].values
train_images = train_images.astype(np.float)
print(train_images.shape)
# For labels
train_labels_flat = train_data[['5']].values.ravel()
train_labels_count = np.unique(train_labels_flat).shape[0]
train_images=train_images/255
print(train_labels_flat)

test_images = test_data.iloc[:,1:].values
test_images = test_images.astype(np.float)
print(test_images.shape)
# For labels
test_labels_flat = test_data[['7']].values.ravel()
test_labels_count = np.unique(test_labels_flat).shape[0]
test_images=test_images/255
print(test_labels_flat)

(59999, 784)
[0 4 1 ... 5 6 8]
(9999, 784)
[2 1 0 ... 4 5 6]


In [5]:
small_train_x=[]
small_train_y=[]
for i in range(0,4999):
    small_train_x.append(train_images[i])
    small_train_y.append(train_labels_flat[i])
small_test_x=[]
small_test_y=[]
for i in range(5000,5499):
    small_test_x.append(train_images[i])
    small_test_y.append(train_labels_flat[i])
small_train_y=np.array(small_train_y)
small_train_x=np.array(small_train_x)
small_test_y=np.array(small_test_y)
small_test_x=np.array(small_test_x)

In [6]:
features = train_data.columns[1:]
x_train=train_data[features]

features = test_data.columns[1:]
x_test=test_data[features]
y_train=train_data['5']
y_test=test_data['7']

In [7]:

#x_train, x_test, y_train, y_test = train_test_split(x_train, y_train,
#                                                            test_size=0.10,
#                                                            random_state=42)

In [8]:

param_C = 200
param_gamma = 0.01
classifier = svm.SVC( kernel="rbf",C=param_C,gamma=param_gamma)

# We learn the digits on train part
start_time = dt.datetime.now()
print('Start learning at {}'.format(str(start_time)))
classifier.fit(train_images, train_labels_flat)
end_time = dt.datetime.now() 
print('Stop learning {}'.format(str(end_time)))
elapsed_time= end_time - start_time
print('Elapsed learning {}'.format(str(elapsed_time)))

Start learning at 2018-11-07 15:40:23.139173
Stop learning 2018-11-07 15:45:41.569431
Elapsed learning 0:05:18.430258


In [9]:
# Now predict the value of the test
expected = test_labels_flat
predicted = classifier.predict(test_images)

print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
      
cm = metrics.confusion_matrix(expected, predicted)
print("Confusion matrix:\n%s" % cm)

#plot_confusion_matrix(cm)

print("Accuracy={}".format(metrics.accuracy_score(expected, predicted)))




Classification report for classifier SVC(C=200, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

          0       0.98      0.99      0.99       980
          1       0.99      0.99      0.99      1135
          2       0.98      0.98      0.98      1032
          3       0.98      0.98      0.98      1010
          4       0.98      0.98      0.98       982
          5       0.98      0.98      0.98       892
          6       0.99      0.99      0.99       958
          7       0.98      0.98      0.98      1027
          8       0.98      0.98      0.98       974
          9       0.97      0.97      0.97      1009

avg / total       0.98      0.98      0.98      9999


Confusion matrix:
[[ 973    0    2    0    0    2    0    1    2    0]
 [   0 1129    3    0    0  

In [18]:
gamma_range = np.outer(np.logspace(-3, 0, 4),np.array([1,5]))
gamma_range = gamma_range.flatten()

# generate matrix with all C
#C_range = np.outer(np.logspace(-3, 3, 7),np.array([1,2, 5]))
C_range = np.outer(np.logspace(-1, 1, 3),np.array([1,5]))
# flatten matrix, change to 1D numpy array
C_range = C_range.flatten()

print(gamma_range[7])
print(C_range)

5.0
[ 0.1  0.5  1.   5.  10.  50. ]
